
def get_emojis():
	conceptos_con_emojis = {
      "Captación": "💰",
      "Seguro de Vida": "👨‍👩‍👧‍👦🛡️",  # Representa una familia y un escudo
      "Portabilidad": "📲",
      "Seguro de Salud": "🏥🛡️",
      "Crédito de Nómina": "💳🧾",
      "Seguro de Auto": "🚗🛡️",
      "Seguro de Hogar": "🏡🛡️",
      "Fondos": "💰💼",
      "Pagarés": "📝",
      "Tarjeta de Crédito": "💳",
      "Crédito Hipotecario": "🏠🏦",
      "PPI": "💸",
      "Crédito de Auto": "🚗💳",
      "EFI": "💵",
      "ILC": "📈💳"
    }
	return conceptos_con_emojis

def assigne_emoj(string, emoj):
	string = string.replace('Credito','Crédito').replace('Pagares','Pagarés').replace('Captacion','Captación').replace('Nomina','Nómina')
	for con, em in emoj.items():
		mostrar = em + con
		string = string.replace(con,mostrar)
	return string


def modelo(lista_top):
	return "Rock Clásico"


def get_genders():
	return ['acoustic',
 'punk-rock',
 'progressive-house',
 'power-pop',
 'pop',
 'pop-film',
 'piano',
 'party',
 'pagode',
 'opera',
 'new-age',
 'mpb',
 'minimal-techno',
 'metalcore',
 'metal',
 'mandopop',
 'malay',
 'latino',
 'latin',
 'kids',
 'k-pop',
 'jazz',
 'j-rock',
 'j-pop',
 'j-idol',
 'j-dance',
 'iranian',
 'psych-rock',
 'punk',
 'afrobeat',
 'r-n-b',
 'turkish',
 'trip-hop',
 'trance',
 'techno',
 'tango',
 'synth-pop',
 'swedish',
 'study',
 'spanish',
 'soul',
 'songwriter',
 'sleep',
 'ska',
 'singer-songwriter',
 'show-tunes',
 'sertanejo',
 'samba',
 'salsa',
 'sad',
 'romance',
 'rockabilly',
 'rock',
 'rock-n-roll',
 'reggaeton',
 'reggae',
 'industrial',
 'indie',
 'indie-pop',
 'indian',
 'disney',
 'disco',
 'detroit-techno',
 'deep-house',
 'death-metal',
 'dancehall',
 'dance',
 'country',
 'comedy',
 'club',
 'classical',
 'chill',
 'children',
 'chicago-house',
 'cantopop',
 'british',
 'breakbeat',
 'brazil',
 'blues',
 'bluegrass',
 'black-metal',
 'anime',
 'ambient',
 'alternative',
 'alt-rock',
 'drum-and-bass',
 'dub',
 'dubstep',
 'groove',
 'idm',
 'house',
 'honky-tonk',
 'hip-hop',
 'heavy-metal',
 'hardstyle',
 'hardcore',
 'hard-rock',
 'happy',
 'guitar',
 'grunge',
 'grindcore',
 'edm',
 'goth',
 'gospel',
 'german',
 'garage',
 'funk',
 'french',
 'forro',
 'folk',
 'emo',
 'electronic',
 'electro',
 'world-music']
